// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_pod

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func PodDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"container_disk_in_gb": schema.Int64Attribute{
				Computed:            true,
				Description:         "Container disk size in GB",
				MarkdownDescription: "Container disk size in GB",
			},
			"cost_per_hr": schema.Float64Attribute{
				Computed:            true,
				Description:         "Cost per hour",
				MarkdownDescription: "Cost per hour",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "Creation timestamp",
				MarkdownDescription: "Creation timestamp",
			},
			"desired_status": schema.StringAttribute{
				Computed:            true,
				Description:         "Desired pod status",
				MarkdownDescription: "Desired pod status",
			},
			"docker_args": schema.StringAttribute{
				Computed:            true,
				Description:         "Docker arguments",
				MarkdownDescription: "Docker arguments",
			},
			"env": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Environment variables",
				MarkdownDescription: "Environment variables",
			},
			"gpu_count": schema.Int64Attribute{
				Computed:            true,
				Description:         "Number of GPUs allocated",
				MarkdownDescription: "Number of GPUs allocated",
			},
			"gpu_type_id": schema.StringAttribute{
				Computed:            true,
				Description:         "GPU type ID",
				MarkdownDescription: "GPU type ID",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The pod ID",
				MarkdownDescription: "The pod ID",
			},
			"image_name": schema.StringAttribute{
				Computed:            true,
				Description:         "Docker image name",
				MarkdownDescription: "Docker image name",
			},
			"machine_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Machine ID where pod is running",
				MarkdownDescription: "Machine ID where pod is running",
			},
			"machine_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Machine type",
				MarkdownDescription: "Machine type",
			},
			"memory_in_gb": schema.Float64Attribute{
				Computed:            true,
				Description:         "Memory allocated in GB",
				MarkdownDescription: "Memory allocated in GB",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Pod name",
				MarkdownDescription: "Pod name",
			},
			"ports": schema.StringAttribute{
				Computed:            true,
				Description:         "Port configuration",
				MarkdownDescription: "Port configuration",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Current pod status (RUNNING, STOPPED, etc.)",
				MarkdownDescription: "Current pod status (RUNNING, STOPPED, etc.)",
			},
			"template_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Template ID used for this pod",
				MarkdownDescription: "Template ID used for this pod",
			},
			"volume_in_gb": schema.Float64Attribute{
				Computed:            true,
				Description:         "Volume size in GB",
				MarkdownDescription: "Volume size in GB",
			},
			"volume_mount_path": schema.StringAttribute{
				Computed:            true,
				Description:         "Volume mount path",
				MarkdownDescription: "Volume mount path",
			},
		},
	}
}

type PodModel struct {
	ContainerDiskInGb types.Int64   `tfsdk:"container_disk_in_gb"`
	CostPerHr         types.Float64 `tfsdk:"cost_per_hr"`
	CreatedAt         types.String  `tfsdk:"created_at"`
	DesiredStatus     types.String  `tfsdk:"desired_status"`
	DockerArgs        types.String  `tfsdk:"docker_args"`
	Env               types.List    `tfsdk:"env"`
	GpuCount          types.Int64   `tfsdk:"gpu_count"`
	GpuTypeId         types.String  `tfsdk:"gpu_type_id"`
	Id                types.String  `tfsdk:"id"`
	ImageName         types.String  `tfsdk:"image_name"`
	MachineId         types.String  `tfsdk:"machine_id"`
	MachineType       types.String  `tfsdk:"machine_type"`
	MemoryInGb        types.Float64 `tfsdk:"memory_in_gb"`
	Name              types.String  `tfsdk:"name"`
	Ports             types.String  `tfsdk:"ports"`
	Status            types.String  `tfsdk:"status"`
	TemplateId        types.String  `tfsdk:"template_id"`
	VolumeInGb        types.Float64 `tfsdk:"volume_in_gb"`
	VolumeMountPath   types.String  `tfsdk:"volume_mount_path"`
}
