// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_endpoint_worker

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func EndpointWorkerResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"container_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Container ID",
				MarkdownDescription: "Container ID",
			},
			"endpoint_id": schema.StringAttribute{
				Required:            true,
				Description:         "Endpoint ID",
				MarkdownDescription: "Endpoint ID",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Worker ID",
				MarkdownDescription: "Worker ID",
			},
			"idle_seconds": schema.Int64Attribute{
				Computed:            true,
				Description:         "Seconds since worker was last busy",
				MarkdownDescription: "Seconds since worker was last busy",
			},
			"last_busy_ms": schema.Int64Attribute{
				Computed:            true,
				Description:         "Milliseconds since epoch when worker was last busy",
				MarkdownDescription: "Milliseconds since epoch when worker was last busy",
			},
			"pod_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Pod ID",
				MarkdownDescription: "Pod ID",
			},
			"start_time": schema.StringAttribute{
				Computed:            true,
				Description:         "Worker start time",
				MarkdownDescription: "Worker start time",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Worker status",
				MarkdownDescription: "Worker status",
			},
			"uptime_ms": schema.Int64Attribute{
				Computed:            true,
				Description:         "Worker uptime in milliseconds",
				MarkdownDescription: "Worker uptime in milliseconds",
			},
		},
	}
}

type EndpointWorkerModel struct {
	ContainerId  types.String `tfsdk:"container_id"`
	EndpointId   types.String `tfsdk:"endpoint_id"`
	Id           types.String `tfsdk:"id"`
	IdleSeconds  types.Int64  `tfsdk:"idle_seconds"`
	LastBusyMs   types.Int64  `tfsdk:"last_busy_ms"`
	PodId        types.String `tfsdk:"pod_id"`
	StartTime    types.String `tfsdk:"start_time"`
	Status       types.String `tfsdk:"status"`
	UptimeMs     types.Int64  `tfsdk:"uptime_ms"`
}
