// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_container_registry_auth

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ContainerRegistryAuthDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"container_registry_auths": schema.ListNestedAttribute{
				Computed:            true,
				Description:         "List of container registry auths",
				MarkdownDescription: "List of container registry auths",
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "Container registry auth ID",
							MarkdownDescription: "Container registry auth ID",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Container registry auth name",
							MarkdownDescription: "Container registry auth name",
						},
						"username": schema.StringAttribute{
							Computed:            true,
							Description:         "Container registry username",
							MarkdownDescription: "Container registry username",
						},
					},
				},
			},
		},
	}
}

type ContainerRegistryAuthModel struct {
	Id       types.String `tfsdk:"id"`
	Name     types.String `tfsdk:"name"`
	Username types.String `tfsdk:"username"`
}

type ContainerRegistryAuthDataSourceModel struct {
	ContainerRegistryAuths []ContainerRegistryAuthModel `tfsdk:"container_registry_auths"`
}
