// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_network_volume

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NetworkVolumeResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"data_center_id": schema.StringAttribute{
				Required:            true,
				Description:         "Data center ID where the network volume will be created",
				MarkdownDescription: "Data center ID where the network volume will be created",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Network volume ID (assigned after creation)",
				MarkdownDescription: "Network volume ID (assigned after creation)",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Network volume name",
				MarkdownDescription: "Network volume name",
			},
			"size": schema.Int64Attribute{
				Required:            true,
				Description:         "Size of the network volume in GB",
				MarkdownDescription: "Size of the network volume in GB",
			},
			"type": schema.StringAttribute{
				Optional:            true,
				Description:         "Storage tier: STANDARD or HIGH_PERFORMANCE",
				MarkdownDescription: "Storage tier: STANDARD or HIGH_PERFORMANCE",
			},
		},
	}
}

type NetworkVolumeModel struct {
	DataCenterId   types.String `tfsdk:"data_center_id"`
	Id             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	Size           types.Int64  `tfsdk:"size"`
	Type           types.String `tfsdk:"type"`
}
