// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_machine

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func MachineResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"bid_price_per_gpu": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Bid price per GPU",
				MarkdownDescription: "Bid price per GPU",
			},
			"cpu_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of CPUs",
				MarkdownDescription: "Number of CPUs",
			},
			"data_center_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Data center ID",
				MarkdownDescription: "Data center ID",
			},
			"disk_in_gb": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Disk size in GB",
				MarkdownDescription: "Disk size in GB",
			},
			"gpu_count": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of GPUs",
				MarkdownDescription: "Number of GPUs",
				Default:             int64default.StaticInt64(1),
			},
			"gpu_type_id": schema.StringAttribute{
				Required:            true,
				Description:         "GPU type ID",
				MarkdownDescription: "GPU type ID",
			},
			"host_price_per_gpu": schema.Float64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Host price per GPU",
				MarkdownDescription: "Host price per GPU",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Machine ID",
				MarkdownDescription: "Machine ID",
			},
			"listed": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "List machine for others to use",
				MarkdownDescription: "List machine for others to use",
				Default:             booldefault.StaticBool(true),
			},
			"location": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Location/country code",
				MarkdownDescription: "Location/country code",
			},
			"maintenance_mode": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether in maintenance mode",
				MarkdownDescription: "Whether in maintenance mode",
			},
			"memory_in_gb": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Memory in GB",
				MarkdownDescription: "Memory in GB",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Machine name",
				MarkdownDescription: "Machine name",
			},
			"secure_cloud": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Use secure cloud",
				MarkdownDescription: "Use secure cloud",
				Default:             booldefault.StaticBool(false),
			},
			"verified": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether machine is verified",
				MarkdownDescription: "Whether machine is verified",
			},
		},
	}
}

type MachineModel struct {
	BidPricePerGpu  types.Float64 `tfsdk:"bid_price_per_gpu"`
	CpuCount        types.Int64   `tfsdk:"cpu_count"`
	DataCenterId    types.String  `tfsdk:"data_center_id"`
	DiskInGb        types.Int64   `tfsdk:"disk_in_gb"`
	GpuCount        types.Int64   `tfsdk:"gpu_count"`
	GpuTypeId       types.String  `tfsdk:"gpu_type_id"`
	HostPricePerGpu types.Float64 `tfsdk:"host_price_per_gpu"`
	Id              types.String  `tfsdk:"id"`
	Listed          types.Bool    `tfsdk:"listed"`
	Location        types.String  `tfsdk:"location"`
	MaintenanceMode types.Bool    `tfsdk:"maintenance_mode"`
	MemoryInGb      types.Int64   `tfsdk:"memory_in_gb"`
	Name            types.String  `tfsdk:"name"`
	SecureCloud     types.Bool    `tfsdk:"secure_cloud"`
	Verified        types.Bool    `tfsdk:"verified"`
}
