// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_machine

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func MachineDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cpu_count": schema.Int64Attribute{
				Computed:            true,
				Description:         "CPU count",
				MarkdownDescription: "CPU count",
			},
			"cpu_type_id": schema.StringAttribute{
				Computed:            true,
				Description:         "CPU type ID",
				MarkdownDescription: "CPU type ID",
			},
			"data_center_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Data center ID",
				MarkdownDescription: "Data center ID",
			},
			"disk_reserved": schema.Int64Attribute{
				Computed:            true,
				Description:         "Reserved disk in GB",
				MarkdownDescription: "Reserved disk in GB",
			},
			"disk_total": schema.Int64Attribute{
				Computed:            true,
				Description:         "Total disk in GB",
				MarkdownDescription: "Total disk in GB",
			},
			"gpu_reserved": schema.Int64Attribute{
				Computed:            true,
				Description:         "Reserved GPU count",
				MarkdownDescription: "Reserved GPU count",
			},
			"gpu_total": schema.Int64Attribute{
				Computed:            true,
				Description:         "Total GPU count",
				MarkdownDescription: "Total GPU count",
			},
			"gpu_type_id": schema.StringAttribute{
				Computed:            true,
				Description:         "GPU type ID",
				MarkdownDescription: "GPU type ID",
			},
			"host_price_per_gpu": schema.Float64Attribute{
				Computed:            true,
				Description:         "Host price per GPU",
				MarkdownDescription: "Host price per GPU",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Machine ID",
				MarkdownDescription: "Machine ID",
			},
			"listed": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether machine is listed",
				MarkdownDescription: "Whether machine is listed",
			},
			"location": schema.StringAttribute{
				Computed:            true,
				Description:         "Location/country code",
				MarkdownDescription: "Location/country code",
			},
			"maintenance_mode": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether machine is in maintenance mode",
				MarkdownDescription: "Whether machine is in maintenance mode",
			},
			"memory_reserved": schema.Int64Attribute{
				Computed:            true,
				Description:         "Reserved memory in GB",
				MarkdownDescription: "Reserved memory in GB",
			},
			"memory_total": schema.Int64Attribute{
				Computed:            true,
				Description:         "Total memory in GB",
				MarkdownDescription: "Total memory in GB",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Machine name",
				MarkdownDescription: "Machine name",
			},
			"runpod_ip": schema.StringAttribute{
				Computed:            true,
				Description:         "RunPod IP address",
				MarkdownDescription: "RunPod IP address",
			},
			"secure_cloud": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether machine is in secure cloud",
				MarkdownDescription: "Whether machine is in secure cloud",
			},
			"verified": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether machine is verified",
				MarkdownDescription: "Whether machine is verified",
			},
		},
	}
}

type MachineModel struct {
	CpuCount        types.Int64   `tfsdk:"cpu_count"`
	CpuTypeId       types.String  `tfsdk:"cpu_type_id"`
	DataCenterId    types.String  `tfsdk:"data_center_id"`
	DiskReserved    types.Int64   `tfsdk:"disk_reserved"`
	DiskTotal       types.Int64   `tfsdk:"disk_total"`
	GpuReserved     types.Int64   `tfsdk:"gpu_reserved"`
	GpuTotal        types.Int64   `tfsdk:"gpu_total"`
	GpuTypeId       types.String  `tfsdk:"gpu_type_id"`
	HostPricePerGpu types.Float64 `tfsdk:"host_price_per_gpu"`
	Id              types.String  `tfsdk:"id"`
	Listed          types.Bool    `tfsdk:"listed"`
	Location        types.String  `tfsdk:"location"`
	MaintenanceMode types.Bool    `tfsdk:"maintenance_mode"`
	MemoryReserved  types.Int64   `tfsdk:"memory_reserved"`
	MemoryTotal     types.Int64   `tfsdk:"memory_total"`
	Name            types.String  `tfsdk:"name"`
	RunpodIp        types.String  `tfsdk:"runpod_ip"`
	SecureCloud     types.Bool    `tfsdk:"secure_cloud"`
	Verified        types.Bool    `tfsdk:"verified"`
}
