// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_data_centers

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func DataCentersDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"global_network": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether global network is enabled",
				MarkdownDescription: "Whether global network is enabled",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Data center ID",
				MarkdownDescription: "Data center ID",
			},
			"location": schema.StringAttribute{
				Computed:            true,
				Description:         "Data center location",
				MarkdownDescription: "Data center location",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Data center name",
				MarkdownDescription: "Data center name",
			},
		},
	}
}

type DataCentersModel struct {
	GlobalNetwork types.Bool   `tfsdk:"global_network"`
	Id            types.String `tfsdk:"id"`
	Location      types.String `tfsdk:"location"`
	Name          types.String `tfsdk:"name"`
}
